// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using RealEstateClassificator.Dal;

#nullable disable

namespace RealEstateClassificator.Dal.Migrations
{
    [DbContext(typeof(RealEstateClassificatorContext))]
    [Migration("20231217164629_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("RealEstateClassificator.Dal.Entities.Card", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("BalconiesCount")
                        .HasColumnType("integer");

                    b.Property<int?>("BuiltYear")
                        .HasColumnType("integer");

                    b.Property<int?>("CargoLiftsCount")
                        .HasColumnType("integer");

                    b.Property<string>("City")
                        .HasColumnType("text");

                    b.Property<int?>("ClassOfCard")
                        .HasColumnType("integer");

                    b.Property<int?>("CombinedBathrooms")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<double?>("DistanceToCity")
                        .HasColumnType("double precision");

                    b.Property<string>("District")
                        .HasColumnType("text");

                    b.Property<int?>("Floor")
                        .HasColumnType("integer");

                    b.Property<int?>("Floors")
                        .HasColumnType("integer");

                    b.Property<bool?>("IsStudio")
                        .HasColumnType("boolean");

                    b.Property<double?>("KitchenArea")
                        .HasColumnType("double precision");

                    b.Property<double?>("LivingArea")
                        .HasColumnType("double precision");

                    b.Property<int?>("PassengerLiftsCount")
                        .HasColumnType("integer");

                    b.Property<long>("Price")
                        .HasColumnType("bigint");

                    b.Property<int?>("Renovation")
                        .HasColumnType("integer");

                    b.Property<int?>("Rooms")
                        .HasColumnType("integer");

                    b.Property<int?>("SeparateBathrooms")
                        .HasColumnType("integer");

                    b.Property<double?>("TotalArea")
                        .HasColumnType("double precision");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.ToTable("Card");
                });
#pragma warning restore 612, 618
        }
    }
}
